### ISSUE TITLE
Nachdem man auf Accountsettings war, verschwindet der Adminverwaltungreiter aus der navbar

### ISSUE THREAD

**Issue by cem-dev** [Lordede/socialSport#121]

**Comment by Ainges** [comment]
@cem-dev dann löscht Accountsettings nach einer Bearbeitung das Attribut ob jemand Admin ist aus dem SessionScope, hast du das nicht gemacht?

**Comment by cem-dev** [comment]
Danke für die Hilfe hatte des gar nicht im Kopf, bzw wusste nicht wie der Mechanismus geht, bzw. die getUser Funktion stand schon viel länger als deine Funktion. aber hättest auch das:"user.setIsAdmin(rs.getBoolean("isAdmin"));" einfach ins UserServlet eintragen können, aber danke für die Aufklärung. (ich will dich bloß ärgern)
