### ISSUE TITLE
RegistrationServlet: Prüfung ob Email bereits vorhanden o.ä.

### ISSUE THREAD

**Issue by Lordede** [Lordede/socialSport#26]
TODO: Fehlerausgeben bei nicht verfügbarer E-Mail oder Username
 Wäre es möglich bei der Eingabe schon die Verfügbarkeit zu testen?

Siehe Z. 140ff

**Comment by Ainges** [comment]
Es soll zur Eingabezeit die Eingabe mit einer zuvor gezogenen Liste aller User verglichen werden, ob die E-mail / username noch verfügbar ist.

Korrekt = ✅
Nicht verfügbar = ❌
