### ISSUE TITLE
Sets sollen über Ajax in die DB geschrieben werden

### ISSUE THREAD

**Issue by Lordede** [Lordede/socialSport#57]
readcontent() in TriggerExerciseAddition
-> Servlet erfassen
-> onLoad 

Geht ins Servlet
gibt response zurück (siehe Exerciseservlet)

Sätze sollen in DB hinzugefügt werden

Mit Training verknüpfen (oder mit JoinBean)

**Comment by Lordede** [comment]
Orientieren an TrainingServlet Postmethode

**Comment by Ainges** [comment]
done
