### ISSUE TITLE
Beim erstellen eines Trainings wird eine falsche / keine Uhrzeit üergeben

### ISSUE THREAD

**Issue by Ainges** [Lordede/socialSport#67]
![image](https://user-images.githubusercontent.com/81434615/172842155-1100fb37-0101-44c9-aa7d-ec4162c805da.png)

**Comment by Ainges** [comment]
+ immer 2 Punkte

**Comment by Lordede** [comment]
ggf Übersicht vergangene Trainings hinzufügen
