### ISSUE TITLE
Training Festlegung Übungen mittels JoinServlet

### ISSUE THREAD

**Issue by Ainges** [Lordede/socialSport#75]
Trainign load -> Übungen werden reingeladen ohne sets

**Comment by Ainges** [comment]
+ neue Übungen dürfen nicht hinzugefügt werden

**Comment by Lordede** [comment]
Training wird ausgewählt -> Soll Übungen geladen werden ohne Sets -> Am Besten mit JoinServlet -> mit addExercises auf Hubetus seine JS ansprechen

**Comment by Lordede** [comment]
Prüfen bei Hinzufügen/Laden von Übung, welche Ansicht
